### ISSUE TITLE
What if I want to compile multiple projects?

### ISSUE THREAD

**Issue by lifetin** [hodgef/js-library-boilerplate#1029]
What if I want to compile multiple projects?

Metaphor: Src / AAA/ index.js Corresponding output directory build / AAA

src/bbb/ index.js The corresponding output directory is build / BBB

**Comment by hodgef** [comment]
Hey @lifetin,

If your use-case is very different from the default, I'd recommend using a simpler boilerplate (so it's easier to configure):

- https://github.com/hodgef/js-library-boilerplate-basic (Javascript)
- https://github.com/hodgef/ts-library-boilerplate-basic (Typescript)

But in any case, your solution will probably involve using a dynamic entry point in your Webpack config, like this:
https://github.com/prss-io/slate-dark-theme/blob/master/webpack.config.js#L9

In this case I wanted `src/AAA/index.js` to be built into `build/AAA.js`. You can use a similar logic in your config.

**Comment by lifetin** [comment]
After modification, you can compile several different project libraries
