### ISSUE TITLE
How i can add types at non typescript library

### ISSUE THREAD

**Issue by ilomon10** [hodgef/js-library-boilerplate#1184]
I create library with your boilerplate but i have to add `types definition` to run library on `typescript` project, how do i can add types definition with this boilerplate

This is my library its called [fungsi-maju](https://github.com/ilomon10/fungsi-maju)

**Comment by hodgef** [comment]
Hi @ilomon10,

When I wanted to quickly add types to projects created with this library, I just added a d.ts file that I maintained manually.

Here's an example:

https://github.com/hodgef/simple-keyboard/tree/2.32.0/src/lib/%40types

https://github.com/hodgef/simple-keyboard/blob/56fc194ad6200b8dcb0c6c746c0be93a493b0ae7/config/webpack.config.js#L643

https://github.com/hodgef/simple-keyboard/blob/56fc194ad6200b8dcb0c6c746c0be93a493b0ae7/package.json#L6

Other ways are:

- To integrate Typescript into your project (look for guides about how to integrate TS into create-react-app/CRA).
- To use [**ts-library-boilerplate-basic**](https://github.com/hodgef/ts-library-boilerplate-basic), which uses TS by default. However this one is not based on CRA but is a barebones boilerplate created from scratch.

Regards,
Francisco Hodge

**Comment by ilomon10** [comment]
To clarify the steps to be completed:
1. Add some type definitions manually in `src/@types` directory
2. Install `copy-webpack-plugin` to devDependency
3. Add a constant variable for the path to the types directory in [`src/config/paths.js`](https://github.com/hodgef/simple-keyboard/blob/2.32.0/config/paths.js#L62 )
4. Add the code `copy-webpack-plugin` to copy the type to be created in [`src/config/webpack.config.js`](https://github.com/hodgef/simple-keyboard/blob/56fc194ad6200b8dcb0c6c746c0be93a493b0ae7/config/webpack.config.js#L643)
5. Add type path in [`package.json`](https://github.com/hodgef/simple-keyboard/blob/56fc194ad6200b8dcb0c6c746c0be93a493b0ae7/package.json#L6) to solve with npm
6. Now run the build script

Thank you @hodgef , now i can use my lib on typescript project.
