### ISSUE TITLE
'loose' mode configuration must be the same for 

### ISSUE THREAD

**Issue by lifetin** [hodgef/js-library-boilerplate#1489]
After downloading, I use NPM run start to prompt this error. What settings should I set?

In the past, 2.6.108 was such a problem, and now 2.6.111 is also such a problem

'loose' mode configuration must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods 
and @babel/plugin-proposal-private-property-in-object (when they are enabled).
![22](https://user-images.githubusercontent.com/10474968/161190210-aa94a3a7-c3fb-4fa9-8e23-c7a1d184e804.jpg)

**Comment by hodgef** [comment]
Thanks for reporting this @lifetin! This should be fixed as of the latest commit, please feel free to re-clone the repo.

Regards,
Francisco Hodge
