### ISSUE TITLE
Build library with Async Await syntax without polyfill 

### ISSUE THREAD

**Issue by ilomon10** [hodgef/js-library-boilerplate#1491]
I ever create Async method with async/await syntax but when i build for my nodejs project it require polyfill thing.

```js
class MyLibrary {
  ...
  // Sync method - that i use right now
  register(cb) {
    let someVariable = cb();
    return someVariable;
  }
  // Async method - that i want implement
  async register(cb) {
    let someVariable = await cb();
    return someVariable;
  }
  ...
}
```

Do you have any best practice to make async method with async/await syntax ?

**Comment by hodgef** [comment]
@ilomon10 Are you using the latest version of the repo? This pattern is working for me:

```js
myArrowMethod = async () => {
    const isResolved = await this.myAsyncRequest();
    console.log("isResolved", isResolved);
}

myAsyncRequest = () => {
    return new Promise(resolve => {
        setTimeout(() => resolve(true), 3000);
    });
}
```
![image](https://user-images.githubusercontent.com/25509135/161412561-3cfde99f-9877-43f4-8e9b-97362e62c02c.png)

If so, please feel free to share the full error - thanks!
