### ISSUE TITLE
How to make use of workbox caching?

### ISSUE THREAD

**Issue by irahulranjan** [hodgef/js-library-boilerplate#1612]
I want to use the boilerplate to create a library that can be added from a cdn to other websites, is there any example of configuring workbox to precache the dependencies of the library? I tried adding workbox to an existing boilerplate and the service worker registration fails as the library is hosted on a different domain. Thanks.

**Comment by hodgef** [comment]
Hey @irahulranjan, I'd suggest trying out tutorials on how to Configure Workbox with Create React App (CRA), such as this one:
https://dev.to/divyansh7924/customizing-workbox-with-create-react-app-1ada

This boilerplate is based on CRA so these tutorials should apply to it.

Regards,
Francisco Hodge
