### ISSUE TITLE
Demo vs lib(question)

### ISSUE THREAD

**Issue by jasan-s** [hodgef/js-library-boilerplate#226]
bit unclear as to what the difference and the choice to use between `demo` in `src/` vs `lib` in `src/`. and how `build` vs `demo` are different.  when building for production to be consumed is the build dir the only thing required

**Comment by hodgef** [comment]
Hello @jasan-s,

`./src/demo` is basically your demo page where you can show off your library. This demo is built (to `./demo`) by running `npm run demo`. Once your demo is built, it'll be ready for deployment to Github Pages, etc.

`./src/lib` is the source for the actual library, which is built by running `npm run build`.

All that is meant to be a more complete setup, but if you prefer simplicity I would recommend checking out [s-library-boilerplate-basic](https://github.com/hodgef/js-library-boilerplate-basic) instead.

Regards,
Francisco Hodge

**Comment by jasan-s** [comment]
@hodgef thanks. that makes sense. is the react react-dom in dev-depenecies only for the demo then? is it possible to also add ui component using react into the lib(not the demo)?

**Comment by hodgef** [comment]
Hey @jasan-s,

This boilerplate is based on [create-react-app](https://github.com/facebook/create-react-app), so these dependencies came from there. I basically kept them around in case they're depended upon in the build process

However they are never imported in either the demo or the lib so they won't be part of the bundles.

I'll look into removing these soon just so there's less stuff to install.

Regards,
Francisco Hodge

**Comment by lifetin** [comment]
What if I want to compile multiple projects?

Metaphor: Src / AAA/ index.js Corresponding output directory build / AAA

src/bbb/ index.js The corresponding output directory is build / BBB
