### ISSUE TITLE
TypeError: Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by geongeorge** [hodgef/js-library-boilerplate#278]
I get window.Library undefined when accessing through cdn.
This is the built library: https://www.npmjs.com/package/regex-colorize

**Comment by hodgef** [comment]
Hello @geongeorge,

The library seems to work for me. Here's the sandbox:
https://codesandbox.io/s/festive-wright-m3pen

Feel free to reach out if you still have issues getting it to run.

Regards,
Francisco Hodge

**Comment by geongeorge** [comment]
Sorry, it was a stupid mistake from my part. 
Thanks for the library <3 
used your basic version for canvas-txt before
you can add this into your "made with" section:
https://github.com/geongeorge/regex-colorizer

**Comment by hodgef** [comment]
Will do - Thanks for sharing and keep up the good work !
