### ISSUE TITLE
Demo didn't include bundle when run `npm start`

### ISSUE THREAD

**Issue by ilomon10** [hodgef/js-library-boilerplate#966]
Hi, you created a cool template to speed up library development.

I have some problems.
I created a library called [Fungsi Maju](https://github.com/ilomon10/fungsi-maju) last week but when I ran `npm start` to test at demo, it started without any errors but when changing the script in the demo folder it didn't respond. I think the demo directory is not resolved by webpack, please check my [repo](https://github.com/ilomon10/fungsi-maju).

Btw, npm run demo worked flawlessly.

**Comment by hodgef** [comment]
Hello @ilomon10, thanks for reporting this. I will look into this later today and provide a fix. 

Regards,
Francisco Hodge

**Comment by ilomon10** [comment]
I just remove `&& !shouldUseReactRefresh` and running perfectly

https://github.com/hodgef/js-library-boilerplate/blob/5144a3716c4b220fd2843f1fda4a5bd527a79df2/config/webpack.config.js#L187-L191

**Comment by hodgef** [comment]
Thanks for the heads up, the boilerplate should be fixed now. Turns out adding an .env file with `FAST_REFRESH=false` also does the trick.

https://github.com/facebook/create-react-app/issues/9904#issuecomment-735223010

Regards,
Francisco Hodge
